package fontAwesome

import scala.scalajs.js
import scala.scalajs.js.annotation._

object freeBrands {
  // https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/use-with-node-js/fontawesome-free-brands/index.d.ts
  // using vim:
  // :read !export FAVERSION=5.0.13; curl --silent https://raw.githubusercontent.com/FortAwesome/Font-Awesome/$FAVERSION/advanced-options/use-with-node-js/fontawesome-free-brands/index.d.ts | grep "export const fa" | sed -E "s/export const (.+): IconDefinition;/  @js.native @JSImport(\"@fortawesome\/fontawesome-free-solid\", \"\1\") object \1 extends IconDefinition/"

  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "fa500px") object fa500px extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAccessibleIcon") object faAccessibleIcon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAccusoft") object faAccusoft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAdn") object faAdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAdversal") object faAdversal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAffiliatetheme") object faAffiliatetheme extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAlgolia") object faAlgolia extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAmazon") object faAmazon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAmazonPay") object faAmazonPay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAmilia") object faAmilia extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAndroid") object faAndroid extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAngellist") object faAngellist extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAngrycreative") object faAngrycreative extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAngular") object faAngular extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAppStore") object faAppStore extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAppStoreIos") object faAppStoreIos extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faApper") object faApper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faApple") object faApple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faApplePay") object faApplePay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAsymmetrik") object faAsymmetrik extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAudible") object faAudible extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAutoprefixer") object faAutoprefixer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAvianex") object faAvianex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAviato") object faAviato extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faAws") object faAws extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBandcamp") object faBandcamp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBehance") object faBehance extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBehanceSquare") object faBehanceSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBimobject") object faBimobject extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBitbucket") object faBitbucket extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBitcoin") object faBitcoin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBity") object faBity extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBlackTie") object faBlackTie extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBlackberry") object faBlackberry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBlogger") object faBlogger extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBloggerB") object faBloggerB extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBluetooth") object faBluetooth extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBluetoothB") object faBluetoothB extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBtc") object faBtc extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBuromobelexperte") object faBuromobelexperte extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faBuysellads") object faBuysellads extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcAmazonPay") object faCcAmazonPay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcAmex") object faCcAmex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcApplePay") object faCcApplePay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcDinersClub") object faCcDinersClub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcDiscover") object faCcDiscover extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcJcb") object faCcJcb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcMastercard") object faCcMastercard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcPaypal") object faCcPaypal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcStripe") object faCcStripe extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCcVisa") object faCcVisa extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCentercode") object faCentercode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faChrome") object faChrome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCloudscale") object faCloudscale extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCloudsmith") object faCloudsmith extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCloudversify") object faCloudversify extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCodepen") object faCodepen extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCodiepie") object faCodiepie extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faConnectdevelop") object faConnectdevelop extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faContao") object faContao extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCpanel") object faCpanel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommons") object faCreativeCommons extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsBy") object faCreativeCommonsBy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsNc") object faCreativeCommonsNc extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsNcEu") object faCreativeCommonsNcEu extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsNcJp") object faCreativeCommonsNcJp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsNd") object faCreativeCommonsNd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsPd") object faCreativeCommonsPd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsPdAlt") object faCreativeCommonsPdAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsRemix") object faCreativeCommonsRemix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsSa") object faCreativeCommonsSa extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsSampling") object faCreativeCommonsSampling extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsSamplingPlus") object faCreativeCommonsSamplingPlus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCreativeCommonsShare") object faCreativeCommonsShare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCss3") object faCss3 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCss3Alt") object faCss3Alt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faCuttlefish") object faCuttlefish extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDAndD") object faDAndD extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDashcube") object faDashcube extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDelicious") object faDelicious extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDeploydog") object faDeploydog extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDeskpro") object faDeskpro extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDeviantart") object faDeviantart extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDigg") object faDigg extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDigitalOcean") object faDigitalOcean extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDiscord") object faDiscord extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDiscourse") object faDiscourse extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDochub") object faDochub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDocker") object faDocker extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDraft2digital") object faDraft2digital extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDribbble") object faDribbble extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDribbbleSquare") object faDribbbleSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDropbox") object faDropbox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDrupal") object faDrupal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faDyalog") object faDyalog extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEarlybirds") object faEarlybirds extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEbay") object faEbay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEdge") object faEdge extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faElementor") object faElementor extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEmber") object faEmber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEmpire") object faEmpire extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEnvira") object faEnvira extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faErlang") object faErlang extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEthereum") object faEthereum extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faEtsy") object faEtsy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faExpeditedssl") object faExpeditedssl extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFacebook") object faFacebook extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFacebookF") object faFacebookF extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFacebookMessenger") object faFacebookMessenger extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFacebookSquare") object faFacebookSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFirefox") object faFirefox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFirstOrder") object faFirstOrder extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFirstOrderAlt") object faFirstOrderAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFirstdraft") object faFirstdraft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFlickr") object faFlickr extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFlipboard") object faFlipboard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFly") object faFly extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFontAwesome") object faFontAwesome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFontAwesomeAlt") object faFontAwesomeAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFontAwesomeFlag") object faFontAwesomeFlag extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFontAwesomeLogoFull") object faFontAwesomeLogoFull extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFonticons") object faFonticons extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFonticonsFi") object faFonticonsFi extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFortAwesome") object faFortAwesome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFortAwesomeAlt") object faFortAwesomeAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faForumbee") object faForumbee extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFoursquare") object faFoursquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFreeCodeCamp") object faFreeCodeCamp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFreebsd") object faFreebsd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faFulcrum") object faFulcrum extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGalacticRepublic") object faGalacticRepublic extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGalacticSenate") object faGalacticSenate extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGetPocket") object faGetPocket extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGg") object faGg extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGgCircle") object faGgCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGit") object faGit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGitSquare") object faGitSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGithub") object faGithub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGithubAlt") object faGithubAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGithubSquare") object faGithubSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGitkraken") object faGitkraken extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGitlab") object faGitlab extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGitter") object faGitter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGlide") object faGlide extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGlideG") object faGlideG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGofore") object faGofore extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGoodreads") object faGoodreads extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGoodreadsG") object faGoodreadsG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGoogle") object faGoogle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGoogleDrive") object faGoogleDrive extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGooglePlay") object faGooglePlay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGooglePlus") object faGooglePlus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGooglePlusG") object faGooglePlusG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGooglePlusSquare") object faGooglePlusSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGoogleWallet") object faGoogleWallet extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGratipay") object faGratipay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGrav") object faGrav extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGripfire") object faGripfire extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGrunt") object faGrunt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faGulp") object faGulp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHackerNews") object faHackerNews extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHackerNewsSquare") object faHackerNewsSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHips") object faHips extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHireAHelper") object faHireAHelper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHooli") object faHooli extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHotjar") object faHotjar extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHouzz") object faHouzz extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHtml5") object faHtml5 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faHubspot") object faHubspot extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faImdb") object faImdb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faInstagram") object faInstagram extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faInternetExplorer") object faInternetExplorer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faIoxhost") object faIoxhost extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faItunes") object faItunes extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faItunesNote") object faItunesNote extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJava") object faJava extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJediOrder") object faJediOrder extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJenkins") object faJenkins extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJoget") object faJoget extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJoomla") object faJoomla extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJs") object faJs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJsSquare") object faJsSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faJsfiddle") object faJsfiddle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faKeybase") object faKeybase extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faKeycdn") object faKeycdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faKickstarter") object faKickstarter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faKickstarterK") object faKickstarterK extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faKorvue") object faKorvue extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLaravel") object faLaravel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLastfm") object faLastfm extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLastfmSquare") object faLastfmSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLeanpub") object faLeanpub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLess") object faLess extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLine") object faLine extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLinkedin") object faLinkedin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLinkedinIn") object faLinkedinIn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLinode") object faLinode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLinux") object faLinux extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faLyft") object faLyft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMagento") object faMagento extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMandalorian") object faMandalorian extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMastodon") object faMastodon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMaxcdn") object faMaxcdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMedapps") object faMedapps extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMedium") object faMedium extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMediumM") object faMediumM extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMedrt") object faMedrt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMeetup") object faMeetup extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMicrosoft") object faMicrosoft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMix") object faMix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMixcloud") object faMixcloud extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMizuni") object faMizuni extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faModx") object faModx extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faMonero") object faMonero extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNapster") object faNapster extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNintendoSwitch") object faNintendoSwitch extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNode") object faNode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNodeJs") object faNodeJs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNpm") object faNpm extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNs8") object faNs8 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faNutritionix") object faNutritionix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOdnoklassniki") object faOdnoklassniki extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOdnoklassnikiSquare") object faOdnoklassnikiSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOldRepublic") object faOldRepublic extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOpencart") object faOpencart extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOpenid") object faOpenid extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOpera") object faOpera extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOptinMonster") object faOptinMonster extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faOsi") object faOsi extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPage4") object faPage4 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPagelines") object faPagelines extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPalfed") object faPalfed extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPatreon") object faPatreon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPaypal") object faPaypal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPeriscope") object faPeriscope extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPhabricator") object faPhabricator extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPhoenixFramework") object faPhoenixFramework extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPhoenixSquadron") object faPhoenixSquadron extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPhp") object faPhp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPiedPiper") object faPiedPiper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPiedPiperAlt") object faPiedPiperAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPiedPiperHat") object faPiedPiperHat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPiedPiperPp") object faPiedPiperPp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPinterest") object faPinterest extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPinterestP") object faPinterestP extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPinterestSquare") object faPinterestSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPlaystation") object faPlaystation extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faProductHunt") object faProductHunt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPushed") object faPushed extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faPython") object faPython extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faQq") object faQq extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faQuinscape") object faQuinscape extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faQuora") object faQuora extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRProject") object faRProject extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRavelry") object faRavelry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faReact") object faReact extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faReadme") object faReadme extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRebel") object faRebel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRedRiver") object faRedRiver extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faReddit") object faReddit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRedditAlien") object faRedditAlien extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRedditSquare") object faRedditSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRendact") object faRendact extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRenren") object faRenren extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faReplyd") object faReplyd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faResearchgate") object faResearchgate extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faResolving") object faResolving extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRocketchat") object faRocketchat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faRockrms") object faRockrms extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSafari") object faSafari extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSass") object faSass extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSchlix") object faSchlix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faScribd") object faScribd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSearchengin") object faSearchengin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSellcast") object faSellcast extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSellsy") object faSellsy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faServicestack") object faServicestack extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faShirtsinbulk") object faShirtsinbulk extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSimplybuilt") object faSimplybuilt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSistrix") object faSistrix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSith") object faSith extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSkyatlas") object faSkyatlas extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSkype") object faSkype extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSlack") object faSlack extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSlackHash") object faSlackHash extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSlideshare") object faSlideshare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSnapchat") object faSnapchat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSnapchatGhost") object faSnapchatGhost extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSnapchatSquare") object faSnapchatSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSoundcloud") object faSoundcloud extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSpeakap") object faSpeakap extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSpotify") object faSpotify extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStackExchange") object faStackExchange extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStackOverflow") object faStackOverflow extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStaylinked") object faStaylinked extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSteam") object faSteam extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSteamSquare") object faSteamSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSteamSymbol") object faSteamSymbol extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStickerMule") object faStickerMule extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStrava") object faStrava extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStripe") object faStripe extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStripeS") object faStripeS extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStudiovinari") object faStudiovinari extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStumbleupon") object faStumbleupon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faStumbleuponCircle") object faStumbleuponCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSuperpowers") object faSuperpowers extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faSupple") object faSupple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTeamspeak") object faTeamspeak extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTelegram") object faTelegram extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTelegramPlane") object faTelegramPlane extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTencentWeibo") object faTencentWeibo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faThemeisle") object faThemeisle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTradeFederation") object faTradeFederation extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTrello") object faTrello extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTripadvisor") object faTripadvisor extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTumblr") object faTumblr extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTumblrSquare") object faTumblrSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTwitch") object faTwitch extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTwitter") object faTwitter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTwitterSquare") object faTwitterSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faTypo3") object faTypo3 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUber") object faUber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUikit") object faUikit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUniregistry") object faUniregistry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUntappd") object faUntappd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUsb") object faUsb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faUssunnah") object faUssunnah extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVaadin") object faVaadin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faViacoin") object faViacoin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faViadeo") object faViadeo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faViadeoSquare") object faViadeoSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faViber") object faViber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVimeo") object faVimeo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVimeoSquare") object faVimeoSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVimeoV") object faVimeoV extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVine") object faVine extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVk") object faVk extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVnv") object faVnv extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faVuejs") object faVuejs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWeibo") object faWeibo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWeixin") object faWeixin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWhatsapp") object faWhatsapp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWhatsappSquare") object faWhatsappSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWhmcs") object faWhmcs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWikipediaW") object faWikipediaW extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWindows") object faWindows extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWolfPackBattalion") object faWolfPackBattalion extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWordpress") object faWordpress extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWordpressSimple") object faWordpressSimple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWpbeginner") object faWpbeginner extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWpexplorer") object faWpexplorer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faWpforms") object faWpforms extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faXbox") object faXbox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faXing") object faXing extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faXingSquare") object faXingSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYCombinator") object faYCombinator extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYahoo") object faYahoo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYandex") object faYandex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYandexInternational") object faYandexInternational extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYelp") object faYelp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYoast") object faYoast extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYoutube") object faYoutube extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-solid", "faYoutubeSquare") object faYoutubeSquare extends IconDefinition
}
