package fontAwesome

import scala.scalajs.js
import scala.scalajs.js.annotation._

object freeBrands {
  // https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/use-with-node-js/fontawesome-free-brands/index.d.ts
  // using vim:
  // :read !export FAVERSION=5.0.13; curl --silent https://raw.githubusercontent.com/FortAwesome/Font-Awesome/$FAVERSION/advanced-options/use-with-node-js/fontawesome-free-brands/index.d.ts | grep "export const fa" | sed -E "s/export const (.+): IconDefinition;/  @js.native @JSImport(\"@fortawesome\/fontawesome-free-brands\", \"\1\") object \1 extends IconDefinition/"

  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "fa500px") object fa500px extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAccessibleIcon") object faAccessibleIcon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAccusoft") object faAccusoft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAdn") object faAdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAdversal") object faAdversal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAffiliatetheme") object faAffiliatetheme extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAlgolia") object faAlgolia extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAmazon") object faAmazon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAmazonPay") object faAmazonPay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAmilia") object faAmilia extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAndroid") object faAndroid extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAngellist") object faAngellist extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAngrycreative") object faAngrycreative extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAngular") object faAngular extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAppStore") object faAppStore extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAppStoreIos") object faAppStoreIos extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faApper") object faApper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faApple") object faApple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faApplePay") object faApplePay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAsymmetrik") object faAsymmetrik extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAudible") object faAudible extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAutoprefixer") object faAutoprefixer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAvianex") object faAvianex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAviato") object faAviato extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faAws") object faAws extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBandcamp") object faBandcamp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBehance") object faBehance extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBehanceSquare") object faBehanceSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBimobject") object faBimobject extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBitbucket") object faBitbucket extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBitcoin") object faBitcoin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBity") object faBity extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBlackTie") object faBlackTie extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBlackberry") object faBlackberry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBlogger") object faBlogger extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBloggerB") object faBloggerB extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBluetooth") object faBluetooth extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBluetoothB") object faBluetoothB extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBtc") object faBtc extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBuromobelexperte") object faBuromobelexperte extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faBuysellads") object faBuysellads extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcAmazonPay") object faCcAmazonPay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcAmex") object faCcAmex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcApplePay") object faCcApplePay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcDinersClub") object faCcDinersClub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcDiscover") object faCcDiscover extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcJcb") object faCcJcb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcMastercard") object faCcMastercard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcPaypal") object faCcPaypal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcStripe") object faCcStripe extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCcVisa") object faCcVisa extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCentercode") object faCentercode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faChrome") object faChrome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCloudscale") object faCloudscale extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCloudsmith") object faCloudsmith extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCloudversify") object faCloudversify extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCodepen") object faCodepen extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCodiepie") object faCodiepie extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faConnectdevelop") object faConnectdevelop extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faContao") object faContao extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCpanel") object faCpanel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommons") object faCreativeCommons extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsBy") object faCreativeCommonsBy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsNc") object faCreativeCommonsNc extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsNcEu") object faCreativeCommonsNcEu extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsNcJp") object faCreativeCommonsNcJp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsNd") object faCreativeCommonsNd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsPd") object faCreativeCommonsPd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsPdAlt") object faCreativeCommonsPdAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsRemix") object faCreativeCommonsRemix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsSa") object faCreativeCommonsSa extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsSampling") object faCreativeCommonsSampling extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsSamplingPlus") object faCreativeCommonsSamplingPlus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCreativeCommonsShare") object faCreativeCommonsShare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCss3") object faCss3 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCss3Alt") object faCss3Alt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faCuttlefish") object faCuttlefish extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDAndD") object faDAndD extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDashcube") object faDashcube extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDelicious") object faDelicious extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDeploydog") object faDeploydog extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDeskpro") object faDeskpro extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDeviantart") object faDeviantart extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDigg") object faDigg extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDigitalOcean") object faDigitalOcean extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDiscord") object faDiscord extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDiscourse") object faDiscourse extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDochub") object faDochub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDocker") object faDocker extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDraft2digital") object faDraft2digital extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDribbble") object faDribbble extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDribbbleSquare") object faDribbbleSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDropbox") object faDropbox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDrupal") object faDrupal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faDyalog") object faDyalog extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEarlybirds") object faEarlybirds extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEbay") object faEbay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEdge") object faEdge extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faElementor") object faElementor extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEmber") object faEmber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEmpire") object faEmpire extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEnvira") object faEnvira extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faErlang") object faErlang extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEthereum") object faEthereum extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faEtsy") object faEtsy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faExpeditedssl") object faExpeditedssl extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFacebook") object faFacebook extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFacebookF") object faFacebookF extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFacebookMessenger") object faFacebookMessenger extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFacebookSquare") object faFacebookSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFirefox") object faFirefox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFirstOrder") object faFirstOrder extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFirstOrderAlt") object faFirstOrderAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFirstdraft") object faFirstdraft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFlickr") object faFlickr extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFlipboard") object faFlipboard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFly") object faFly extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFontAwesome") object faFontAwesome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFontAwesomeAlt") object faFontAwesomeAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFontAwesomeFlag") object faFontAwesomeFlag extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFontAwesomeLogoFull") object faFontAwesomeLogoFull extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFonticons") object faFonticons extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFonticonsFi") object faFonticonsFi extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFortAwesome") object faFortAwesome extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFortAwesomeAlt") object faFortAwesomeAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faForumbee") object faForumbee extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFoursquare") object faFoursquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFreeCodeCamp") object faFreeCodeCamp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFreebsd") object faFreebsd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faFulcrum") object faFulcrum extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGalacticRepublic") object faGalacticRepublic extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGalacticSenate") object faGalacticSenate extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGetPocket") object faGetPocket extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGg") object faGg extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGgCircle") object faGgCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGit") object faGit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGitSquare") object faGitSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGithub") object faGithub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGithubAlt") object faGithubAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGithubSquare") object faGithubSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGitkraken") object faGitkraken extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGitlab") object faGitlab extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGitter") object faGitter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGlide") object faGlide extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGlideG") object faGlideG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGofore") object faGofore extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGoodreads") object faGoodreads extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGoodreadsG") object faGoodreadsG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGoogle") object faGoogle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGoogleDrive") object faGoogleDrive extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGooglePlay") object faGooglePlay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGooglePlus") object faGooglePlus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGooglePlusG") object faGooglePlusG extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGooglePlusSquare") object faGooglePlusSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGoogleWallet") object faGoogleWallet extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGratipay") object faGratipay extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGrav") object faGrav extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGripfire") object faGripfire extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGrunt") object faGrunt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faGulp") object faGulp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHackerNews") object faHackerNews extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHackerNewsSquare") object faHackerNewsSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHips") object faHips extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHireAHelper") object faHireAHelper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHooli") object faHooli extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHotjar") object faHotjar extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHouzz") object faHouzz extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHtml5") object faHtml5 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faHubspot") object faHubspot extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faImdb") object faImdb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faInstagram") object faInstagram extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faInternetExplorer") object faInternetExplorer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faIoxhost") object faIoxhost extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faItunes") object faItunes extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faItunesNote") object faItunesNote extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJava") object faJava extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJediOrder") object faJediOrder extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJenkins") object faJenkins extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJoget") object faJoget extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJoomla") object faJoomla extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJs") object faJs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJsSquare") object faJsSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faJsfiddle") object faJsfiddle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faKeybase") object faKeybase extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faKeycdn") object faKeycdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faKickstarter") object faKickstarter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faKickstarterK") object faKickstarterK extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faKorvue") object faKorvue extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLaravel") object faLaravel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLastfm") object faLastfm extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLastfmSquare") object faLastfmSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLeanpub") object faLeanpub extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLess") object faLess extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLine") object faLine extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLinkedin") object faLinkedin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLinkedinIn") object faLinkedinIn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLinode") object faLinode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLinux") object faLinux extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faLyft") object faLyft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMagento") object faMagento extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMandalorian") object faMandalorian extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMastodon") object faMastodon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMaxcdn") object faMaxcdn extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMedapps") object faMedapps extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMedium") object faMedium extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMediumM") object faMediumM extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMedrt") object faMedrt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMeetup") object faMeetup extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMicrosoft") object faMicrosoft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMix") object faMix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMixcloud") object faMixcloud extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMizuni") object faMizuni extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faModx") object faModx extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faMonero") object faMonero extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNapster") object faNapster extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNintendoSwitch") object faNintendoSwitch extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNode") object faNode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNodeJs") object faNodeJs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNpm") object faNpm extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNs8") object faNs8 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faNutritionix") object faNutritionix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOdnoklassniki") object faOdnoklassniki extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOdnoklassnikiSquare") object faOdnoklassnikiSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOldRepublic") object faOldRepublic extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOpencart") object faOpencart extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOpenid") object faOpenid extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOpera") object faOpera extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOptinMonster") object faOptinMonster extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faOsi") object faOsi extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPage4") object faPage4 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPagelines") object faPagelines extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPalfed") object faPalfed extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPatreon") object faPatreon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPaypal") object faPaypal extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPeriscope") object faPeriscope extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPhabricator") object faPhabricator extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPhoenixFramework") object faPhoenixFramework extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPhoenixSquadron") object faPhoenixSquadron extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPhp") object faPhp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPiedPiper") object faPiedPiper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPiedPiperAlt") object faPiedPiperAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPiedPiperHat") object faPiedPiperHat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPiedPiperPp") object faPiedPiperPp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPinterest") object faPinterest extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPinterestP") object faPinterestP extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPinterestSquare") object faPinterestSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPlaystation") object faPlaystation extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faProductHunt") object faProductHunt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPushed") object faPushed extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faPython") object faPython extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faQq") object faQq extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faQuinscape") object faQuinscape extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faQuora") object faQuora extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRProject") object faRProject extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRavelry") object faRavelry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faReact") object faReact extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faReadme") object faReadme extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRebel") object faRebel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRedRiver") object faRedRiver extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faReddit") object faReddit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRedditAlien") object faRedditAlien extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRedditSquare") object faRedditSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRendact") object faRendact extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRenren") object faRenren extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faReplyd") object faReplyd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faResearchgate") object faResearchgate extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faResolving") object faResolving extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRocketchat") object faRocketchat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faRockrms") object faRockrms extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSafari") object faSafari extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSass") object faSass extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSchlix") object faSchlix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faScribd") object faScribd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSearchengin") object faSearchengin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSellcast") object faSellcast extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSellsy") object faSellsy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faServicestack") object faServicestack extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faShirtsinbulk") object faShirtsinbulk extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSimplybuilt") object faSimplybuilt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSistrix") object faSistrix extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSith") object faSith extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSkyatlas") object faSkyatlas extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSkype") object faSkype extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSlack") object faSlack extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSlackHash") object faSlackHash extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSlideshare") object faSlideshare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSnapchat") object faSnapchat extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSnapchatGhost") object faSnapchatGhost extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSnapchatSquare") object faSnapchatSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSoundcloud") object faSoundcloud extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSpeakap") object faSpeakap extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSpotify") object faSpotify extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStackExchange") object faStackExchange extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStackOverflow") object faStackOverflow extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStaylinked") object faStaylinked extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSteam") object faSteam extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSteamSquare") object faSteamSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSteamSymbol") object faSteamSymbol extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStickerMule") object faStickerMule extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStrava") object faStrava extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStripe") object faStripe extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStripeS") object faStripeS extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStudiovinari") object faStudiovinari extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStumbleupon") object faStumbleupon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faStumbleuponCircle") object faStumbleuponCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSuperpowers") object faSuperpowers extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faSupple") object faSupple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTeamspeak") object faTeamspeak extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTelegram") object faTelegram extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTelegramPlane") object faTelegramPlane extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTencentWeibo") object faTencentWeibo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faThemeisle") object faThemeisle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTradeFederation") object faTradeFederation extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTrello") object faTrello extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTripadvisor") object faTripadvisor extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTumblr") object faTumblr extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTumblrSquare") object faTumblrSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTwitch") object faTwitch extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTwitter") object faTwitter extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTwitterSquare") object faTwitterSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faTypo3") object faTypo3 extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUber") object faUber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUikit") object faUikit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUniregistry") object faUniregistry extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUntappd") object faUntappd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUsb") object faUsb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faUssunnah") object faUssunnah extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVaadin") object faVaadin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faViacoin") object faViacoin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faViadeo") object faViadeo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faViadeoSquare") object faViadeoSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faViber") object faViber extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVimeo") object faVimeo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVimeoSquare") object faVimeoSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVimeoV") object faVimeoV extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVine") object faVine extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVk") object faVk extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVnv") object faVnv extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faVuejs") object faVuejs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWeibo") object faWeibo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWeixin") object faWeixin extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWhatsapp") object faWhatsapp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWhatsappSquare") object faWhatsappSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWhmcs") object faWhmcs extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWikipediaW") object faWikipediaW extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWindows") object faWindows extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWolfPackBattalion") object faWolfPackBattalion extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWordpress") object faWordpress extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWordpressSimple") object faWordpressSimple extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWpbeginner") object faWpbeginner extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWpexplorer") object faWpexplorer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faWpforms") object faWpforms extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faXbox") object faXbox extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faXing") object faXing extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faXingSquare") object faXingSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYCombinator") object faYCombinator extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYahoo") object faYahoo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYandex") object faYandex extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYandexInternational") object faYandexInternational extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYelp") object faYelp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYoast") object faYoast extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYoutube") object faYoutube extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-brands", "faYoutubeSquare") object faYoutubeSquare extends IconDefinition
}
