package fontAwesome

import scala.scalajs.js
import scala.scalajs.js.annotation._

object freeRegular {
  // https://github.com/FortAwesome/Font-Awesome/blob/master/advanced-options/use-with-node-js/fontawesome-free-regular/index.d.ts
  // using vim:
  // :read !export FAVERSION=5.0.13; curl --silent https://raw.githubusercontent.com/FortAwesome/Font-Awesome/$FAVERSION/advanced-options/use-with-node-js/fontawesome-free-regular/index.d.ts | grep "export const fa" | sed -E "s/export const (.+): IconDefinition;/  @js.native @JSImport(\"@fortawesome\/fontawesome-free-regular\", \"\1\") object \1 extends IconDefinition/"

  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faAddressBook") object faAddressBook extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faAddressCard") object faAddressCard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faArrowAltCircleDown") object faArrowAltCircleDown extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faArrowAltCircleLeft") object faArrowAltCircleLeft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faArrowAltCircleRight") object faArrowAltCircleRight extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faArrowAltCircleUp") object faArrowAltCircleUp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faBell") object faBell extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faBellSlash") object faBellSlash extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faBookmark") object faBookmark extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faBuilding") object faBuilding extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendar") object faCalendar extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendarAlt") object faCalendarAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendarCheck") object faCalendarCheck extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendarMinus") object faCalendarMinus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendarPlus") object faCalendarPlus extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCalendarTimes") object faCalendarTimes extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCaretSquareDown") object faCaretSquareDown extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCaretSquareLeft") object faCaretSquareLeft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCaretSquareRight") object faCaretSquareRight extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCaretSquareUp") object faCaretSquareUp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faChartBar") object faChartBar extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCheckCircle") object faCheckCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCheckSquare") object faCheckSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCircle") object faCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faClipboard") object faClipboard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faClock") object faClock extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faClone") object faClone extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faClosedCaptioning") object faClosedCaptioning extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faComment") object faComment extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCommentAlt") object faCommentAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCommentDots") object faCommentDots extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faComments") object faComments extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCompass") object faCompass extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCopy") object faCopy extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCopyright") object faCopyright extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faCreditCard") object faCreditCard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faDotCircle") object faDotCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faEdit") object faEdit extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faEnvelope") object faEnvelope extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faEnvelopeOpen") object faEnvelopeOpen extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faEye") object faEye extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faEyeSlash") object faEyeSlash extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFile") object faFile extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileAlt") object faFileAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileArchive") object faFileArchive extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileAudio") object faFileAudio extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileCode") object faFileCode extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileExcel") object faFileExcel extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileImage") object faFileImage extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFilePdf") object faFilePdf extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFilePowerpoint") object faFilePowerpoint extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileVideo") object faFileVideo extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFileWord") object faFileWord extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFlag") object faFlag extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFolder") object faFolder extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFolderOpen") object faFolderOpen extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFontAwesomeLogoFull") object faFontAwesomeLogoFull extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFrown") object faFrown extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faFutbol") object faFutbol extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faGem") object faGem extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandLizard") object faHandLizard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPaper") object faHandPaper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPeace") object faHandPeace extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPointDown") object faHandPointDown extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPointLeft") object faHandPointLeft extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPointRight") object faHandPointRight extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPointUp") object faHandPointUp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandPointer") object faHandPointer extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandRock") object faHandRock extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandScissors") object faHandScissors extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandSpock") object faHandSpock extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHandshake") object faHandshake extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHdd") object faHdd extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHeart") object faHeart extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHospital") object faHospital extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faHourglass") object faHourglass extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faIdBadge") object faIdBadge extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faIdCard") object faIdCard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faImage") object faImage extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faImages") object faImages extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faKeyboard") object faKeyboard extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faLemon") object faLemon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faLifeRing") object faLifeRing extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faLightbulb") object faLightbulb extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faListAlt") object faListAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faMap") object faMap extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faMeh") object faMeh extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faMinusSquare") object faMinusSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faMoneyBillAlt") object faMoneyBillAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faMoon") object faMoon extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faNewspaper") object faNewspaper extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faObjectGroup") object faObjectGroup extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faObjectUngroup") object faObjectUngroup extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faPaperPlane") object faPaperPlane extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faPauseCircle") object faPauseCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faPlayCircle") object faPlayCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faPlusSquare") object faPlusSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faQuestionCircle") object faQuestionCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faRegistered") object faRegistered extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faSave") object faSave extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faShareSquare") object faShareSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faSmile") object faSmile extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faSnowflake") object faSnowflake extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faSquare") object faSquare extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faStar") object faStar extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faStarHalf") object faStarHalf extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faStickyNote") object faStickyNote extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faStopCircle") object faStopCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faSun") object faSun extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faThumbsDown") object faThumbsDown extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faThumbsUp") object faThumbsUp extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faTimesCircle") object faTimesCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faTrashAlt") object faTrashAlt extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faUser") object faUser extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faUserCircle") object faUserCircle extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faWindowClose") object faWindowClose extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faWindowMaximize") object faWindowMaximize extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faWindowMinimize") object faWindowMinimize extends IconDefinition
  @js.native @JSImport("@fortawesome/fontawesome-free-regular", "faWindowRestore") object faWindowRestore extends IconDefinition
}

